// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdzoslgjemunetuztrfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkem9zbGdqZW11bmV0dXp0cmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTY3MDUsImV4cCI6MjA2MjQ3MjcwNX0.xsst0bXRT5Jh2waGCeJHN344Jeu20dTa15S46ceYkOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);